
package vista.juego;

import dominio.Jugador;
import java.awt.Color;
import java.awt.Dimension;
import java.lang.reflect.InvocationTargetException;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;

/**
 *
 * @author brawun
 */
public class PnlJugador extends javax.swing.JPanel {

    /**
     * Instancia del jugador al desplegar.
     */
    private Jugador jugador;

    /**
     * Crea PnlJugador.
     * @param jugador
     */
    public PnlJugador(Jugador jugador) {
        initComponents();
        this.setSize(new Dimension(265, 83));
        this.jugador = jugador;
        if(!this.jugador.getRutaColor().isBlank()){
            this.labelColor.setIcon(new ImageIcon("src/main/resources/colores/" + this.jugador.getRutaColor()));
        }
        this.labelNombre.setText(this.jugador.getNombre());
        this.lblPuntos.setText(this.jugador.getPuntaje() + "");
        if(this.jugador.getColor() != null){
            this.setBackground(Color.decode(this.jugador.getColor()));
        }
    }
    
    /**
     * Establece el jugador.
     * @param jugador 
     */
    public void setJugador(Jugador jugador){
        this.jugador = jugador;
    }
    
    /**
     * Establece el puntaje de un jugador.
     * @param puntaje 
     */
    public void setPuntaje(int puntaje){
        this.jugador.setPuntaje(puntaje);
        this.lblPuntos.setText(String.valueOf(puntaje));
        this.lblPuntos.revalidate();
    }
    
   public void actualizarPuntaje() throws InterruptedException, InvocationTargetException {
    SwingUtilities.invokeLater(() -> {
        this.lblPuntos.setText(String.valueOf(this.jugador.getPuntaje()));
        this.lblPuntos.repaint();
    });
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelColor = new javax.swing.JLabel();
        lblPuntos = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();

        labelColor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        labelColor.setMaximumSize(new java.awt.Dimension(50, 50));
        labelColor.setMinimumSize(new java.awt.Dimension(50, 50));
        labelColor.setPreferredSize(new java.awt.Dimension(50, 50));

        lblPuntos.setFont(new java.awt.Font("Warung Kopi", 1, 14)); // NOI18N
        lblPuntos.setForeground(new java.awt.Color(0, 51, 102));
        lblPuntos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPuntos.setText("0");
        lblPuntos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lblPuntos.setMaximumSize(new java.awt.Dimension(50, 50));
        lblPuntos.setMinimumSize(new java.awt.Dimension(50, 50));
        lblPuntos.setPreferredSize(new java.awt.Dimension(50, 50));

        labelNombre.setFont(new java.awt.Font("Warung Kopi", 0, 18)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(0, 51, 102));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelColor, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelColor, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelColor;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel lblPuntos;
    // End of variables declaration//GEN-END:variables
}